satisfaction:
    resource: "@SatisfactionBundle/Controller/"
    type:     annotation
    prefix:   /


# redirecting the root
root:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /hello/you
    permanent: true

